Проект 15 спринта. Попытка 1
AlexandraLesnykh/java-shareit2 pull request #1
Opened 2023-04-19 22:20 UTC by AlexandraLesnykh

2023-04-23 11:15 UTC, AlexandraLesnykh commented
Проект 15 спринта. 1 Итерация. Добавлена возможность добавления запросов, пагинация и тестирование.

2023-04-23 18:42 UTC, db-exp requested changes

2023-04-23 18:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from == 4 && size == 2) {
не понял)

2023-04-23 18:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +Optional<User> findByEmail(String email);
форматирование поехало

2023-04-23 18:42 UTC, db-exp commented on src/main/resources/schema.sql
> +    name varchar (256) NOT NULL,
256 - много, как мне кажется

2023-04-23 18:42 UTC, db-exp commented on src/main/resources/schema.sql
> +    email varchar (256) NOT NULL CHECK (email LIKE '%@%.%'),
и тут

2023-04-23 18:42 UTC, db-exp commented on src/main/resources/schema.sql
> +    comment_text varchar NOT NULL,
давай явно добавим размерность

2023-04-23 18:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        //  Page<Booking> bookingsPage = repository.findAll(Sort.by(Sort.Direction.DESC, "start"), pageRequest);
лучше удалить

2023-04-23 18:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        //listForReturn.clear();
давай удалим

2023-04-23 18:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/exeptions/ValidationException.java
> +public class ValidationException extends Exception {
лучше отнаследовать от  RuntimeException

2023-04-23 18:42 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    //User requestor;
Давай удалим

2023-04-24 09:47 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +Optional<User> findByEmail(String email);
Исправлено

2023-04-24 09:48 UTC, AlexandraLesnykh commented on src/main/resources/schema.sql
> +    name varchar (256) NOT NULL,
Исправила

2023-04-24 09:48 UTC, AlexandraLesnykh commented on src/main/resources/schema.sql
> +    email varchar (256) NOT NULL CHECK (email LIKE '%@%.%'),
Исправила

2023-04-24 09:49 UTC, AlexandraLesnykh commented on src/main/resources/schema.sql
> +    comment_text varchar NOT NULL,
Добавила

2023-04-24 09:50 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        //  Page<Booking> bookingsPage = repository.findAll(Sort.by(Sort.Direction.DESC, "start"), pageRequest);
Удалено

2023-04-24 09:50 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        //listForReturn.clear();
Удалено

2023-04-24 09:51 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/exeptions/ValidationException.java
> +public class ValidationException extends Exception {
Сделано

2023-04-24 09:51 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    //User requestor;
Удалено

2023-04-24 19:45 UTC, AlexandraLesnykh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from == 4 && size == 2) {
Это я решила, что в тестах постман закралась ошибка. Но, как выяснилось, ошибка была в моем коде) Исправила.

2023-04-24 19:58 UTC, AlexandraLesnykh commented
Проект 15 спринта. Итерация 2. Поправлены размерности. Внесены корректировки в методы получения всех бронирований

2023-04-24 20:16 UTC, db-exp approved these changes

2023-05-05 20:27 UTC, merged