Add docker
AlexandraLesnykh/java-shareit2 pull request #2
Opened 2023-05-05 20:26 UTC by AlexandraLesnykh

2023-05-05 22:30 UTC, AlexandraLesnykh commented
Проект 16 спринта. Разделение приложения на 2 части, настройка запуска через Docker. Итерация 1.

2023-05-06 14:49 UTC, db-exp requested changes

2023-05-06 14:49 UTC, db-exp commented on docker-compose.yml
> +      - "6541:5432"
базу наружу в случае использования только контейнером можно и не открывать

2023-05-06 14:49 UTC, db-exp commented on gateway/Dockerfile
Лучше еще явно прописывать какой порт 
EXPOSE 8080

2023-05-06 14:49 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/requests/dto/ItemRequestRequestDto.java
> +    long requestor;
можно еще NonNull

2023-05-06 14:49 UTC, db-exp commented on server/Dockerfile
Лучше еще явно прописывать какой порт 
EXPOSE порт

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		System.setProperty("server.port", "9090");
Не понял зачем) ?

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +  //  Page<Booking> findAllByOrderByStartDesc(Pageable pageRequest);
давай удалим

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/comments/dto/CommentDto.java
> +    @NonNull
на сервере уже валидация не нужна, она на gateway

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/exeptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
все проверки валидации на gateway в этом задании должны быть

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://db:5432/shareit
Передается же через env переменную

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
в модели   long id;

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    // @NonNull
удаляем?)

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
в модели long id;

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
в модели long id;

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
в модели long id;

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
в модели long id;

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    requestor INTEGER REFERENCES users (id) ON DELETE RESTRICT,
тут long

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    owner INTEGER REFERENCES users (id) ON DELETE RESTRICT,
тут long

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    item_id INTEGER REFERENCES items (id) ON DELETE RESTRICT,
тут и ниже long

2023-05-06 14:49 UTC, db-exp commented on server/src/main/resources/schema.sql
> +    item_id INTEGER REFERENCES items (id) ON DELETE RESTRICT,
тут и ниже long

2023-05-06 14:49 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +										  @RequestParam(name = "state", defaultValue = "all") String stateParam,
Как вариант можно сделать кастомную валидацию и повесить на параметр

https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

https://stackoverflow.com/questions/24582842/is-it-possible-to-validate-requestparam-in-spring-mvc-rest-endpoint

2023-05-06 14:49 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	public ResponseEntity<Object> create(@RequestHeader("X-Sharer-User-Id") long userId,
Тут может тоже лучше NonNull?

2023-05-06 14:49 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	public ResponseEntity<Object> getBookingById(@RequestHeader("X-Sharer-User-Id") long userId,
Тут может тоже лучше NonNull?

2023-05-06 14:49 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/dto/CommentRequestDto.java
> +    long itemId;
Тут может тоже лучше NonNull?

2023-05-06 14:49 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/dto/CommentRequestDto.java
> +    long authorId;
Тут может тоже лучше NonNull?

2023-05-06 14:49 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +public class ItemController {
На long параметры тоже может NonNull добавить?

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStart() == null || booking.getEnd() == null || booking.getStart().equals(booking.getEnd())) {
валидацию лучше в gateway

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (!item.isAvailable() || item.getName().isEmpty() || item.getDescription() == null) {
валидацию нужно вынести в gateway

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
В сервисах лучше использовать "чужие" сервисы, а не репозитории

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                               @RequestParam(name = "from", defaultValue = "0") Integer from,
валидацию нужно переместить в gateway

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                      @RequestParam(name = "from", required = false, defaultValue = "0") Integer from,
валидацию нужно переместить в gateway

2023-05-06 14:49 UTC, db-exp commented on server/src/test/java/ru/practicum/shareit/ControllerTest/BookingControllerTest.java
> +/*
удалим?

2023-05-06 14:49 UTC, db-exp commented on server/src/test/java/ru/practicum/shareit/ControllerTest/ItemControllerTest.java
> +  /*  @Test
давай удалим

2023-05-06 14:49 UTC, db-exp commented on server/src/test/java/ru/practicum/shareit/ControllerTest/ItemControllerTest.java
> +    @Test
и это давай удалим

2023-05-06 14:49 UTC, db-exp commented on server/src/test/java/ru/practicum/shareit/ControllerTest/ItemRequestControllerTest.java
> + /*   @Test
давай удалим

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(name = "from", defaultValue = "0") Integer from,
валидация должна быть в gateway

2023-05-06 14:49 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                    @RequestParam(name = "from", defaultValue = "0") Integer from,
валидация должна быть в gateway

2023-05-07 19:20 UTC, AlexandraLesnykh commented on gateway/Dockerfile
сделано

2023-05-07 19:21 UTC, AlexandraLesnykh commented on gateway/src/main/java/ru/practicum/shareit/requests/dto/ItemRequestRequestDto.java
> +    long requestor;
добавлено

2023-05-07 19:22 UTC, AlexandraLesnykh commented on server/Dockerfile
сделано

2023-05-07 19:23 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/ShareItServer.java
> +		System.setProperty("server.port", "9090");
Была проблема подключения к серверу через докер. Решала разными способами, этот не помог) Удалила.

2023-05-07 19:24 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +  //  Page<Booking> findAllByOrderByStartDesc(Pageable pageRequest);
сделано

2023-05-07 19:25 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/comments/dto/CommentDto.java
> +    @NonNull
пропустила этот момент. удалила.

2023-05-07 19:29 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    // @NonNull
конечно)

2023-05-07 19:32 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
исправлено

2023-05-07 19:34 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
исправлено

2023-05-07 19:34 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
исправлено

2023-05-07 19:34 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
исправлено

2023-05-07 19:34 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
исправлено

2023-05-07 19:34 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    requestor INTEGER REFERENCES users (id) ON DELETE RESTRICT,
исправлено

2023-05-07 19:35 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    owner INTEGER REFERENCES users (id) ON DELETE RESTRICT,
исправлено

2023-05-07 19:35 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    item_id INTEGER REFERENCES items (id) ON DELETE RESTRICT,
исправлено

2023-05-07 19:35 UTC, AlexandraLesnykh commented on server/src/main/resources/schema.sql
> +    item_id INTEGER REFERENCES items (id) ON DELETE RESTRICT,
исправлено

2023-05-07 19:36 UTC, AlexandraLesnykh commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	public ResponseEntity<Object> create(@RequestHeader("X-Sharer-User-Id") long userId,
добавила

2023-05-07 19:37 UTC, AlexandraLesnykh commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	public ResponseEntity<Object> getBookingById(@RequestHeader("X-Sharer-User-Id") long userId,
добавила

2023-05-07 19:38 UTC, AlexandraLesnykh commented on gateway/src/main/java/ru/practicum/shareit/item/dto/CommentRequestDto.java
> +    long itemId;
Добавила

2023-05-07 19:38 UTC, AlexandraLesnykh commented on gateway/src/main/java/ru/practicum/shareit/item/dto/CommentRequestDto.java
> +    long authorId;
Добавила

2023-05-07 19:40 UTC, AlexandraLesnykh commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +public class ItemController {
Добавила

2023-05-07 19:43 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStart() == null || booking.getEnd() == null || booking.getStart().equals(booking.getEnd())) {
сделано

2023-05-07 19:45 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (!item.isAvailable() || item.getName().isEmpty() || item.getDescription() == null) {
Было перенесено в gateway, отсюда убрать забыла. Удалила

2023-05-07 20:00 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                               @RequestParam(name = "from", defaultValue = "0") Integer from,
Сделано

2023-05-07 20:00 UTC, AlexandraLesnykh commented on server/src/test/java/ru/practicum/shareit/ControllerTest/BookingControllerTest.java
> +/*
Удалила

2023-05-07 20:01 UTC, AlexandraLesnykh commented on server/src/test/java/ru/practicum/shareit/ControllerTest/ItemControllerTest.java
> +  /*  @Test
удалила

2023-05-07 20:02 UTC, AlexandraLesnykh commented on server/src/test/java/ru/practicum/shareit/ControllerTest/ItemControllerTest.java
> +    @Test
удалила

2023-05-07 20:02 UTC, AlexandraLesnykh commented on server/src/test/java/ru/practicum/shareit/ControllerTest/ItemRequestControllerTest.java
> + /*   @Test
удалила

2023-05-08 19:33 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/exeptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
Сделано

2023-05-08 19:34 UTC, AlexandraLesnykh commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +										  @RequestParam(name = "state", defaultValue = "all") String stateParam,
Сделала кастомную валидацию по твоему примеру на параметре state. Спасибо за ссылки!

2023-05-08 19:36 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
убрала зависимость от UserReposotory. От BookingRepository оставила, потому что возникает проблема цикличной зависимости сервисов друг от друга.

2023-05-08 19:37 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                      @RequestParam(name = "from", required = false, defaultValue = "0") Integer from,
Здесь нет параметра state, больше нечего валидировать.

2023-05-08 19:38 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(name = "from", defaultValue = "0") Integer from,
Сделан кастомный валидатор на параметр  state

2023-05-08 19:38 UTC, AlexandraLesnykh commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                    @RequestParam(name = "from", defaultValue = "0") Integer from,
Сделан кастомный валидатор на параметр state

2023-05-08 19:57 UTC, AlexandraLesnykh commented
Создана кастомная валидация параметра state в Booking, убрана зависимость ItemService от UserRepository.

2023-05-09 08:17 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
В этом как раз и смысл) 
Допустим тут bookingRepository используется для комментариев и чтобы было хорошо есть смысл вынести сервис комментариев и тогда зависимость будет слабее - попробуй это поправить к следующему спринту

2023-05-09 08:26 UTC, db-exp requested changes

2023-05-09 08:26 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +										  @RequestParam(name = "state", defaultValue = "all") String stateParam,
Молодец! Только кажется, его тут в виде аннотации не хватает и тогда ниже не нужно будет IllegalArgumentException делать

2023-05-09 08:28 UTC, db-exp commented
Про BookingService и ItemService
Допустим тут bookingRepository используется для комментариев и чтобы было хорошо есть смысл вынести сервис комментариев и тогда зависимость будет слабее - старайся учитывать это. Дробить на сервисы не плохо, плохо делать сервисы с многочисленной ответственностью

2023-05-09 09:55 UTC, AlexandraLesnykh commented
Я аннотацию @StateValidation поставила над параметром в BookingClient, потому что в случае отсутствия state, котроллер делает его дефолтным и тогда аннотация работает верно. Иначе до дефолта не доходило, и все падало в ошибку 500. Лишнюю строку с llegalArgumentException соответственно удалила.

2023-05-11 05:26 UTC, AlexandraLesnykh commented
Проект 16 спринта, Итерация 3. Аннотация @StateValidation указана в классе BookingClient.

2023-05-11 05:31 UTC, AlexandraLesnykh commented
Без IllegalArgumentException в BookingController некоторые тесты падают, в пачке никто не смог мне с этим помочь. Наставник вообще сказал, что эта аннотация лишняя. Можем оставить проект в том виде, в котором он есть сейчас и пойти дальше?)

2023-05-11 14:55 UTC, db-exp approved these changes

2023-05-11 17:27 UTC, merged